name: DevJams
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  url_launcher:
  flutter_custom_clippers:

  shared_preferences:
  fluttertoast: ^3.0.4

  qrcode_reader: ^0.4.4
  flip_card:
  qr_flutter:
  intro_slider: ^2.2.8

  snaplist:
  indexed_list_view:

  flutter_svg:

  flutter_launcher_icons: 

flutter_icons:
  # android: "launcher_icon" 
  # ios: true
  # image_path: "lib/assests/aboutus.png"
  ios: true
  android: true
  image_path_ios: 'lib/assests/DevJamsLogo.png'
  image_path_android: 'lib/assests/DevJamsLogo.png'

dev_dependencies:
  http: ^0.12.0+1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:

    - lib/assests/DSCVITLogo.png
    - lib/assests/dev.webp
    - lib/assests/DevJamsLogo.png
    - lib/assests/one.png
    - lib/assests/two.png
    - lib/assests/three.jpg
    - lib/assests/four.jpg
    - lib/assests/five.png
    - lib/assests/six.JPG
    - lib/assests/seven.jpeg
    - lib/assests/eight.jpg
    - lib/assests/nine.JPG
    - lib/assests/ten.png

    - lib/assests/Abhi.jpg
    - lib/assests/Abhishek.jpg
    - lib/assests/Aditya.jpg
    - lib/assests/Akshat.jpeg
    - lib/assests/Amogh.jpg
    - lib/assests/Ananya.jpg
    - lib/assests/Angad.jpeg
    - lib/assests/Apoorva.jpg
    - lib/assests/Arjun.jpeg
    - lib/assests/eight.jpg
    - lib/assests/Ayush.jpg
    - lib/assests/Cyril.jpg
    - lib/assests/DeepakM.jpeg
    - lib/assests/DeepakT.jpg
    - lib/assests/Dhiraj.jpeg
    - lib/assests/Dhruv.jpg
    - lib/assests/Ekaansh.jpeg
    - lib/assests/Hardik.JPEG
    - lib/assests/Kritika.JPG
    - lib/assests/Manorama.jpg
    - lib/assests/Meher.JPG
    - lib/assests/Muskan.jpg
    - lib/assests/Naynika.jpeg
    - lib/assests/Nikhil.jpeg
    - lib/assests/Paritosh.jpg
    - lib/assests/Prateek.png
    - lib/assests/preethi.JPG
    - lib/assests/Purushottam.jpeg
    - lib/assests/Riddhi.JPG
    - lib/assests/Riya.jpg
    - lib/assests/Ruchika.jpeg
    - lib/assests/Saloni.jpg
    - lib/assests/Samarth.jpg
    - lib/assests/Samyak.jpg
    - lib/assests/Sanchi.jpeg
    - lib/assests/Satkriti.jpg
    - lib/assests/Shravani.jpg
    - lib/assests/Shreya.jpeg
    - lib/assests/Shubham.jpg
    - lib/assests/Ubaid.jpg
    - lib/assests/Vikrame.jpg
    - lib/assests/Vishaal.jpg
    - lib/assests/Vivek.jpg
    - lib/assests/Yaswant.JPG

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: lib/fonts/MyFlutterApp.ttf

    - family: Campton
      fonts:
        - asset: lib/fonts/CamptonExtraBold.ttf
#         - asset: fonts/Schyler-Italic.ttf
#           style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
